name: acapy-integration-tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.repository == 'hyperledger/aries-cloudagent-python') || (github.event_name != 'pull_request')
    steps:
      - name: checkout-acapy
        uses: actions/checkout@v3
        with:
          path: acapy
      #- name: run-von-network
      #  uses: ./acapy/.github/actions/run-von-network
      #- name: run-indy-tails-server
      #  uses: ./acapy/.github/actions/run-indy-tails-server
      - name: run-integration-tests
        uses: ./acapy/.github/actions/run-integration-tests
        # to run with a specific set of tests include the following parameter:
        # with:
        #   TEST_SCOPE: "-t @T001-RFC0037"
