name: Tests (Indy)

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      indy-version:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  tests:
    name: Test Python ${{ inputs.python-version }} on Indy ${{ inputs.indy-version }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache image layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-test
          key: ${{ runner.os }}-buildx-test-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-test-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test image
        uses: docker/build-push-action@v3
        with:
          load: true
          context: .
          file: docker/Dockerfile.indy
          target: acapy-test
          tags: acapy-test:latest
          build-args: |
            python_version=${{ inputs.python-version }}
            indy_version=${{ inputs.indy-version }}
          cache-from: type=local,src=/tmp/.buildx-cache-test
          cache-to: type=local,dest=/tmp/.buildx-cache-test-new,mode=max

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-test
          mv /tmp/.buildx-cache-test-new /tmp/.buildx-cache-test

      - name: Run pytest
        run: |
          docker run --rm acapy-test:latest
